### PR TITLE
Report skeleton

### PR DESCRIPTION
**Pull request by SergeyKanzhelev**
See rendered version here:

http://htmlpreview.github.io/?https://github.com/w3c/distributed-tracing/blob/sergkanz/reportDraft/report.html

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
Publishing this PR for initial feedback. Please note this repository may be removed and re-created. Hold on significant discussions.

**Comment by yurishkuro** [comment]
nit - the keys/values are not trimmed in the examples of Trace-Context-Ext

**Comment by yurishkuro** [comment]
html is for machines, not for humans. I suggest limiting its scope to the template only, and define all sections in human-readable markdown files.

**Comment by SergeyKanzhelev** [comment]
Moved here: https://github.com/w3c/tracecontext-spec/pull/47

@yurishkuro  thanks for feedback. I'll address it in new (old) repo

**Pull request closed without merging**
